version: 2.1
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build-test:
    docker:
      - image: circleci/elixir:1.10
        environment:
          MIX_ENV: test
          DATABASE_URL: postgres://voomex@localhost/voomex_test
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: voomex
          POSTGRES_DB: voomex_test
          POSTGRES_PASSWORD:
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: curl https://pre-commit.com/install-local.py | python -

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run: mix deps.get

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run: pre-commit run --all-files
      - run: mix coveralls.circleci
      - slack/status:
          success_message: ":caktus: ${CIRCLE_BRANCH} tests passed. <${CIRCLE_BUILD_URL}|Build> :successful:"
          failure_message: ":sadcactus: ${CIRCLE_BRANCH} tests failed. <${CIRCLE_BUILD_URL}|Build> :failed:"
          include_project_field: false
          include_job_number_field: false
          include_visit_job_action: false

workflows:
  version: 2
  build-test:
    jobs:
      - build-test
